### ISSUE TITLE
"My Hunted Listings" for both hunter and huntee?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/WorkHuntr#100]
Both sides cannot be the same. One is the hunter.

"Hunted Listing" is just a confusing term. "In progress" ?

![image](https://user-images.githubusercontent.com/228704/113622739-5e03ce80-962b-11eb-9c24-545054142cee.png)

**Comment by jhill08** [comment]
![In progress](https://user-images.githubusercontent.com/55595871/114232466-ec3cc500-9949-11eb-95f4-cfc03c04bf77.jpg)
I changed "My Hunted Listings" header to "In Progress" to avoid confusion

**Comment by josemvidal** [comment]
When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit, where X is the issue number you want to close. See [linking pull requests to issues using keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information.

You should also write "#X" on any commit that is for #X. See my [github tips list](https://capstone.cse.sc.edu/lecture/github/#tips) for all the tips.
