### ISSUE TITLE
User can modify job that is currently being worked on

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/WorkHuntr#101]
If you know how URLs work, you can change the price of a contract after it has been accepted:

https://user-images.githubusercontent.com/228704/113623572-8b04b100-962c-11eb-966f-db47d777fe07.mp4

**Comment by jhill08** [comment]
In listing.views, I put a constraint on modify listings only allowing the listing to be modified if the listing was owned by the lister and the status was 'Strutting' which will prevent the listing from being modified after it is claimed.

**Comment by josemvidal** [comment]
When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit, where X is the issue number you want to close. See [linking pull requests to issues using keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information.

You should also write "#X" on any commit that is for #X. See my [github tips list](https://capstone.cse.sc.edu/lecture/github/#tips) for all the tips.
