### ISSUE TITLE
Clicking listing description doesn't give full description.

### ISSUE THREAD

**Issue by ICanNomNoms** [SCCapstone/WorkHuntr#103]
When you click on listing description the button moves up and a description is put below. I don't think this is the full description. Also you might want to remove the button and replace it with the description instead of having it appear below.

https://user-images.githubusercontent.com/44646798/113778088-f799b180-96f9-11eb-9283-e0c01592cd30.mp4

**Comment by jhill08** [comment]
Removed accordion style buttons from listing description categories and replaced the buttons with listing descriptions.

**Comment by jhill08** [comment]
![description](https://user-images.githubusercontent.com/55595871/114232615-1e4e2700-994a-11eb-9f1c-2d0ebf9dd586.jpg)
