### ISSUE TITLE
Able to modify another user's post

### ISSUE THREAD

**Issue by bcrockerT** [SCCapstone/WorkHuntr#107]
When you change the post number in the URL you can modify any post you want
https://workhuntr.herokuapp.com/modify_listings/5/ to https://workhuntr.herokuapp.com/modify_listings/6/ allows changing of the next post.

https://user-images.githubusercontent.com/60371711/113942883-a22fd400-97cf-11eb-9902-5affa4c02399.mp4

**Comment by noahshaw11** [comment]
This issue was resolved while resolving another issue.
