### ISSUE TITLE
404 and debug reveal information

### ISSUE THREAD

**Issue by bcrockerT** [SCCapstone/WorkHuntr#108]
When you go to a URL that does not exist you are given all the paths of the website.
When going to a profile that doesn't exist you are given an entire debug page that reveals some information you may not want known.

https://user-images.githubusercontent.com/60371711/113943244-431e8f00-97d0-11eb-804a-158ad58183d6.mp4

**Comment by noahshaw11** [comment]
We need to remember to set `Debug = False` in the `settings.py` file when deployed. By doing this, no debug information will be leaked to the user. Only a standard 404 page will be displayed.
