### ISSUE TITLE
No Method to Change Hunter/Huntee Status

### ISSUE THREAD

**Issue by jhm-usc** [SCCapstone/WorkHuntr#113]
There seems to be no way to change from being a huntee to a hunter without making a new profile. Maybe even include 2 sub-profiles for hunter and huntee if I wanted to look for people to work on a project while looking for a side project

![hunter-huntee](https://user-images.githubusercontent.com/42620415/114283336-3c358d80-9a17-11eb-8686-c692a5ec08cc.png)

**Comment by noahshaw11** [comment]
Requiring the user to create two separate accounts to access Huntee and Hunter features is intended. We wanted to separate the functionalities as much as possible. This is related to issue #114.
