### ISSUE TITLE
Able to Create 2 Accounts with 1 email

### ISSUE THREAD

**Issue by jhm-usc** [SCCapstone/WorkHuntr#114]
I was able to create 2 separate accounts with 2 different usernames for 1 email

![hunter-huntee](https://user-images.githubusercontent.com/42620415/114283503-13fa5e80-9a18-11eb-956a-1d87d9406bfa.png)

![profile2](https://user-images.githubusercontent.com/42620415/114283507-18267c00-9a18-11eb-9b33-fc2166319f31.png)

**Comment by noahshaw11** [comment]
Allowing the user to create two accounts with the same email is okay as long as the usernames are different between the accounts. We require this. This is intended so users can create a Huntee and a Hunter account with the same email if they desire, but they can also create multiple Huntee accounts or multiple Hunter accounts. This is related to issue #113.
