### ISSUE TITLE
Test login doesn't work

### ISSUE THREAD

**Issue by goodecf** [SCCapstone/WorkHuntr#116]
Trying to login with the test user information:
Email: testworkhuntr@gmail.com
Password: G1antN3rds21

Produces the error:
![image](https://user-images.githubusercontent.com/47934210/115166775-da160180-a082-11eb-97f2-75b8238414cf.png)

**Comment by tbollman** [comment]
The email address provided is to replace a personal email address if you don't feel comfortable giving that information when creating a new account. You must still create a new account either using the test email or a personal one.

**Comment by tbollman** [comment]
Also, if attempting to run the application on your local machine, you must migrate the models in order to set up the database. Please test off of the deployed version to avoid this: workhuntr.herokuapp.com
