### ISSUE TITLE
Add Beta Issues

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/WorkHuntr#51]
Please add all the features you will implement for the [Beta Milestone](https://capstone.cse.sc.edu/milestone/beta/) as Issues, with label:enhancement, and associate them with the Beta Milestone.

When you are done adding your Beta Issues, close this Issue. I will then take a look at them and might comment on them, ask you add more, etc. In the end I will approve the issues and paste their numbers right in here.

Please add your Beta Issues by **January 25**.

**Comment by josemvidal** [comment]
The core functionality of this app is the CRUDing of job posting, and the matching of users to jobs, maybe also interactions between the matched users.

Do your Beta Issues implement this core functionality? It seems so, but I'm not sure what already works. Answer below.

**Comment by noahshaw11** [comment]
Currently, users can post job listings, sign up for job listings, and move job listings to completed. We need to implement the progress tracker feature so users that sign up for jobs can provide regular updates to the ones that posted the jobs. We also need to implement the messaging system so users can communicate with one another without leaving the app. We also need to add a (now dummy) payment screen so users can be paid for their work once they complete a particular listing. Finally, we need to add a search feature so users can search for listings based on specific keywords or tags. The posted issues accomplish these things.

**Comment by josemvidal** [comment]
Sounds good. Beta Issues approved: #52 #53 #54 #55 #56 #57 #58 #59 #60 #61 #62 #63 #64 #65 #68 #69 #70 #71 #72 #73 #74 #75 #66 👍
