### ISSUE TITLE
6.4 Login to Paypal, ApplePay, Bank Account information

### ISSUE THREAD

**Issue by jhill08** [SCCapstone/WorkHuntr#53]
Users should be able to pay with another form of payment such as PayPal, ApplePay, or bank account information

**Comment by josemvidal** [comment]
We will not be able to test payment methods, as these typically require money or similar.

So, there is no need to implement the final payment, for this class. You can implement the dialogs to the the info (credit card number, etc.) and then just pretend it worked.

**Comment by jhill08** [comment]
A mock payment page was created that the huntee can complete to issue payment to the hunter that completed the listing.
