### ISSUE TITLE
Add RC1 Issues

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/WorkHuntr#80]
You should be working on your RC1 release now. Make sure you:

- [ ] Move all open Issues to [RC1](https://capstone.cse.sc.edu/milestone/rc1/) (or close with `label:wontfix`, always explain why you closed). Typical workflow: everything that did not get done for the last release gets moved to the next.
- [ ] Add all your new RC1 Issues. RC1 is your feature-freeze complete release. Everything should be implemented by then.
- [ ] Assign every person to at least one Issue, no more than one person per Issue. Some Issues might be unassigned because you don't yet know who will do them.

Close this when done. Try to get this done by  **March 15** or so.

**Comment by noahshaw11** [comment]
All the issues that we can think of have been added. Our bonus feature is labeled.
