### ISSUE TITLE
Add Description Dropdown for Listings

### ISSUE THREAD

**Issue by noahshaw11** [SCCapstone/WorkHuntr#84]
When a listing is clicked, a dropdown should appear that displays the description of the listing.

**Comment by jhill08** [comment]
An accordion drops down when listing description is clicked and displays listing description.

**Comment by jhill08** [comment]
![Current Listings](https://user-images.githubusercontent.com/55595871/111233363-3d63ce00-85c3-11eb-8a6b-719530cadb95.jpg)
![Description](https://user-images.githubusercontent.com/55595871/111233371-3fc62800-85c3-11eb-9ffe-163d92fdea7c.jpg)

**Comment by jhill08** [comment]
Above is an example of what was done but is subject to change.
