### ISSUE TITLE
Add the Ability to Customize Milestone Amount and Name

### ISSUE THREAD

**Issue by noahshaw11** [SCCapstone/WorkHuntr#87]
The user can input how many milestones they want and what their names will be for each listing.

**Comment by tbollman** [comment]
After spending several days working over several different attempts, we were unable to create custom milestones for the user without breaking other areas of our current codebase along with the changes. The most recent attempt at this can be viewed in the CustomMilestones branch. We believe Django is not setup for this type of implementation and would require us to integrate other services to make work properly.
